#!/usr/bin/env bash
set -e
# mkall - Make all .pdf .epub and .html files
# Usage: mkall
# Required: [gitlab.com/pepa65/TNBT](mkhtm mkpdfs mkepub) coreutils(mkdir)

# Make webpages
simple=html/index.htm indexed=html/index.html
[[ -d html ]] || mkdir -p html
echo -n "Producing '$simple' " >&2
./mkhtm >"$simple"
echo '- done'
echo -n "Producing '$indexed' " >&2
./mkidx "$simple" >"$indexed"
echo '- done'

# Make pdf files
./mkpdfs

# Make epub
./mkepub
