#!/usr/bin/env bash
set -e
# mkall - Make all .pdf .epub and .html files
# Usage: mkall
# Required: [gitlab.com/pepa65/TNBT](mkhtm mkpdfs mkepub) coreutils(mkdir)

# Make webpages
htm=html/TNBT-NT.htm html=html/TNBT-NT.html
[[ -d html ]] || mkdir -p html
# Non-indexed
echo -n "Producing '$htm' " >&2
./mkhtm >"$htm"
echo '- done'
# Indexed
echo -n "Producing '$html' " >&2
./mkidx "$htm" >"$html"
echo '- done'
# Pages to serve
./mksrv

# Make pdf files
./mkpdfs

# Make epub
./mkepub
